-- Deadline alerts generated by the scheduled worker at the 90/30/7-day
-- thresholds. The unique constraint makes the worker idempotent — it can run
-- daily without producing duplicate alerts.

create type deadline_type as enum ('benchmark', 'arcx');
create type alert_channel as enum ('email', 'sms', 'in_app');
create type alert_status as enum ('pending', 'sent', 'dismissed');

create table alerts (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references organizations (id) on delete cascade,
  building_id    uuid not null references buildings (id) on delete cascade,
  deadline_type  deadline_type not null,
  deadline_date  date not null,
  threshold_days smallint not null check (threshold_days in (90, 30, 7)),
  channel        alert_channel not null default 'in_app',
  status         alert_status not null default 'pending',
  created_at     timestamptz not null default now(),
  unique (building_id, deadline_type, deadline_date, threshold_days, channel)
);

create index on alerts (org_id);
create index on alerts (building_id);
